# Generated by Django 4.1.4 on 2022-12-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmailcategory',
            name='date',
        ),
    ]
