# Generated by Django 4.1.4 on 2022-12-16 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('news', 'Новости'), ('post', 'Статьи')], default='post', max_length=4),
        ),
    ]
